version: 2
updates:
    - package-ecosystem: github-actions
      directory: /
      schedule:
          interval: monthly
          time: "06:00"
          timezone: Europe/Berlin
      labels:
          - dependencies
      open-pull-requests-limit: 5

    - package-ecosystem: docker
      directory: /
      schedule:
          interval: monthly
          time: "06:15"
          timezone: Europe/Berlin
      labels:
          - dependencies
      open-pull-requests-limit: 5
